# Generated by Django 4.0.3 on 2022-04-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0002_submission_text_submission_title_submission_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('karma', models.IntegerField(default=1)),
                ('about', models.TextField(default='')),
                ('email', models.EmailField(max_length=60)),
                ('showdead', models.BooleanField()),
                ('noprocrast', models.BooleanField()),
                ('maxvisit', models.CharField(max_length=16)),
                ('minaway', models.CharField(max_length=16)),
                ('delay', models.CharField(max_length=16)),
                ('created_at', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='url',
            field=models.URLField(default='', max_length=50),
        ),
    ]
