# Generated by Django 4.0.3 on 2022-04-05 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0003_user_alter_submission_text_alter_submission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='author',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submission',
            name='type',
            field=models.CharField(default='url', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
