# Generated by Django 4.0.3 on 2022-04-06 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0005_submission_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
