# Generated by Django 4.0.3 on 2022-04-06 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0007_remove_submission_posted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='posted_at_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
