# Generated by Django 4.0.3 on 2022-04-07 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0008_alter_submission_posted_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackernews.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at_date', models.DateField(default=django.utils.timezone.now)),
                ('posted_at_time', models.TimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackernews.user')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hackernews.comment')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackernews.submission')),
            ],
        ),
    ]
