# Generated by Django 4.0.3 on 2022-04-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0009_alter_submission_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.CharField(default='', max_length=15),
        ),
    ]
