# Generated by Django 4.0.3 on 2022-04-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0015_remove_submission_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='comments',
        ),
    ]
