# Generated by Django 4.0.3 on 2022-04-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0016_remove_submission_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
