# Generated by Django 4.0.3 on 2022-04-23 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackernews', '0017_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='authUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='delay',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='maxvisit',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='minaway',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='noprocrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='showdead',
            field=models.BooleanField(default=False),
        ),
    ]
