# Generated by Django 4.0.3 on 2022-04-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0018_remove_user_username_user_authuser_alter_user_delay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
