# Generated by Django 2.2.12 on 2022-04-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0017_auto_20220420_1157'),
        ('hackernews', '0019_remove_user_email'),
    ]

    operations = [
    ]
